version: '3.8'

services:
  mdm_postgres_db:
    image: postgres:16.3-alpine  # Use a recent stable Alpine image for smaller size
    container_name: mdm_postgres_db
    environment:
      POSTGRES_DB: mdm_db
      POSTGRES_USER: mdmuser
      POSTGRES_PASSWORD: mdm_password
    ports:
      - "5432:5432"
    volumes:
      - mdm_pg_data:/var/lib/postgresql/data # Persistent data volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mdmuser -d mdm_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mdm_pg_data: